---
title: "Prediction Model"
output: html_document
date: "2024-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading libraries
```{r}
library(ggplot2)
```

# Reading the data
```{r}
insurance = read.csv("insurance.csv")
summary(insurance)
```

# Cleaning the Data
```{r}
sum(is.na(insurance))
insurance_clean = na.omit(insurance)
insurance_filled = insurance
insurance_filled$age = ifelse(is.na(insurance_filled$age), mean(insurance_filled$age, na.rm = TRUE), insurance_filled$age)
```

# Full Model
```{r}
full_model = lm(charges ~ ., data = insurance_clean)
summary(full_model)
```
# Variable selection using AIC 
```{r}
new_model <- step(full_model, direction = "backward", k=log(nrow(insurance_clean)))
summary(new_model)
```

# Compare full and reduced models via F-Test
```{r}
summary(new_model)
```

```{r}
par(mfrow = c(2, 2))
plot(new_model)
```


```{r}
set.seed(100)
num_rows <- nrow(insurance_data)
training_size <- floor(0.8 * num_rows)
training_indices <- sample(seq_len(num_rows), size = training_size)
training_data <- insurance_data[training_indices, ]
testing_data <- insurance_data[-training_indices, ]
```


```{r}
training_full_model <- lm(charges ~ ., data = training_data)
new_training_model <- step(training_full_model, direction = "backward", k=log(nrow(training_data)))
summary(new_training_model)
```


```{r}
predictions <- predict(new_training_model, newdata = testing_data)
plot(testing_data$charges, predictions, main = "Charges and Predicted Charges Simple Model",
     xlab = "Charges", ylab = "Predicted Charges", pch = 19, col = 'blue')
abline(0, 1, col = "red") 
rsq <- cor(testing_data$charges, predictions)^2
print(rsq)
rmse <- sqrt(mean((testing_data$charges - predictions)^2))
print(paste("RMSE:", rmse))
```