---
title: "Prediction Model"
output: html_document
date: "2024-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading libraries
```{r}
library(ggplot2)
```

# Reading the data
```{r}
insurance = read.csv("insurance.csv")
summary(insurance)
```

# Cleaning the Data
```{r}
sum(is.na(insurance))
insurance_clean = na.omit(insurance)
insurance_filled = insurance
insurance_filled$age = ifelse(is.na(insurance_filled$age), mean(insurance_filled$age, na.rm = TRUE), insurance_filled$age)
```

# Full Model
```{r}

# We want to test the null-hypothesis that bmi is relevant to charges

full_model = lm(charges ~ ., data=insurance_clean)
summary(full_model)
```
# Reduced Model
```{r}
reduced_model = lm(charges ~ age + sex + children + smoker + region, data=insurance_clean)
summary(reduced_model)
```

# Compare full and reduced models via F-Test
```{r}
anova(full_model, reduced_model)

# P-value = 2.2e-16 < 0.05, we reject the null hypothesis, indicating that bmi is not relevant to charges
```

```{r}
par(mfrow = c(2, 2))
plot(reduced_model)

# TO-DO: ANALYZE PLOTS
```
